# Generated by Django 3.1.6 on 2021-03-09 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_account', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
